{% set name = "GHEtool" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GHEtool-{{ version }}.tar.gz
  sha256: 3c6e32022defc8259de8fb5db93edb5b2e85c00f2de86390b632147981ea41e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=54
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - scipy >=1.8.1
    - pygfunction >=2.2.1

test:
  imports:
    - GHEtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wouterpeere/GHEtool
  summary: Python package for borefield sizing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wouterpeere
