{% set name = "GHEtool" %}

{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/ghetool/ghetool-{{ version }}.tar.gz
  sha256: 93522af541465446f7b5b400cb5acf3b64b25f5410e0b47446cc20a5a6942abd


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - pygfunction ==2.3.0
    - scipy >=1.8.1

test:
  imports:
    - GHEtool
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wouterpeere/GHEtool
  summary: Python package for borefield sizing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wouterpeere
