{% set name = "GHEtool" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/15/f0/1671fec387b386c978a9c304659eee5ac7f7f4b9971910d972bb902d0a1a/ghetool-2.2.2.tar.gz
  sha256: 4f345d8a3b3052e948fe83ac8c52aa9438614637f1e160b08287f75d11554c81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=54
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - scipy >=1.8.1
    - pygfunction >=2.2.1

test:
  imports:
    - GHEtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wouterpeere/GHEtool
  summary: Python package for borefield sizing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wouterpeere
