{% set name = "GHEtool" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GHEtool-{{ version }}.tar.gz
  sha256: ca78005aecbbe5d2c9fc5af1153112836654e47ff1d3ee4531c2929e92f7f80f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=54
    - wheel
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - pygfunction >=2.2.1,<2.3.0
    - scipy >=1.8.1

test:
  imports:
    - GHEtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wouterpeere/GHEtool
  summary: Python package for borefield sizing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wouterpeere
